# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c0d81d4d0e764f06b4ace92ec706d9d0963a9fa34d12f3d1be32f720e731083dc5a459401ad62667399f7945f92eaf93165518596285e44fd3db067ab6b9c61

test:
  secret_key_base: 40bef2f22705390d1ebe2205a39202041cb6730e43960bbabb3b4058868e9d088018d7acc8e39982e79ad5eb7b1c389fd6a98e378b7ab1d5f524b58127901990

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
